import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/navbar";
import SearchBar from "../components/search/searchbar";
import Discover from "../components/discover/discover";
import TravelCard from "./../components/travelcard";
import Test from "./../components/test";
import Reviews from "./../components/reviews/reviews";
import Subscribe from "./../components/subscribe/subscribe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Golobe Travel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <NavBar />
        <SearchBar />
        <Discover />
        <TravelCard />
        <Reviews />
      </main>
    </>
  );
}
